# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [4]:
#Type your code here
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [ ]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
df = pd.read_csv("data_clustering.csv")

In [19]:
# Tampilkan 5 baris pertama dengan function head.
df.head(20)

TransactionAmount  TransactionType  Location  Channel  CustomerAge  \
0            0.007207                1        36        0     0.838710   
1            0.195940                1        15        0     0.806452   
2            0.065680                1        23        2     0.016129   
3            0.096016                1        33        2     0.129032   
4            0.047888                1        28        0     0.000000   
5            0.003554                0        39        0     0.306452   
6            0.089199                0        16        1     0.790323   
7            0.055226                0        11        1     0.532258   
8            0.425098                1        26        0     0.596774   
9            0.009130                0         0        2     0.548387   
10           0.098893                1        22        2     0.048387   
11           0.257581                0        23        1     0.096774   
12           0.407275                1        22        0     0.129032   
13           0.086891                1        21        2     0.000000   
14           0.242432                1        10        0     0.290323   
15           0.289517                0         2        1     0.016129   
16           0.256753                1         8        2     0.338710   
17           0.009599                0         0        1     0.661290   
18           0.037116                0         8        2     0.000000   
19           0.030779                1        20        1     0.854839   

    CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance  \
0                    0             0.244828            0.0        0.336832   
1                    0             0.451724            0.0        0.918055   
2                    3             0.158621            0.0        0.068637   
3                    3             0.051724            0.0        0.569198   
4                    3             0.558621            0.0        0.045738   
5                    0             0.444828            0.0        0.888330   
6                    2             0.968966            0.0        0.181155   
7                    1             0.262069            0.0        0.604561   
8                    0             0.379310            0.0        0.061884   
9                    1             0.168966            0.0        0.504026   
10                   3             0.562069            0.0        0.095959   
11                   3             0.348276            0.0        0.102090   
12                   3             0.389655            0.0        0.005945   
13                   3             0.427586            0.0        0.013355   
14                   1             0.410345            0.0        0.226144   
15                   3             0.510345            0.0        0.069236   
16                   1             0.772414            0.0        0.336681   
17                   2             0.331034            0.0        0.527476   
18                   3             0.548276            0.0        0.434728   
19                   2             0.096552            0.0        0.379763   

    Target  
0        2  
1        3  
2        1  
3        2  
4        1  
5        2  
6        3  
7        3  
8        1  
9        0  
10       1  
11       1  
12       1  
13       3  
14       0  
15       0  
16       0  
17       0  
18       0  
19       3

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [21]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
X = df.drop(['Target'], axis=1)
y = df['Target'] #column target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train shape:", X_train.shape, y_train.shape)
print("Test shape:", X_test.shape, y_test.shape)

Train shape: (1917, 9) (1917,)
Test shape: (480, 9) (480,)


# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [24]:
# Buatlah model klasifikasi menggunakan Decision Tree
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42, max_depth=10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluasi model
accuracy = accuracy_score(y_test, y_pred)
print(f"Decision Tree Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Decision Tree Accuracy: 1.0000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       118
           1       1.00      1.00      1.00       123
           2       1.00      1.00      1.00       116
           3       1.00      1.00      1.00       123

    accuracy                           1.00       480
   macro avg       1.00      1.00      1.00       480
weighted avg       1.00      1.00      1.00       480


Confusion Matrix:
[[118   0   0   0]
 [  0 123   0   0]
 [  0   0 116   0]
 [  0   0   0 123]]


In [25]:
# Menyimpan Model
import joblib
joblib.dump(model, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [10]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.

In [11]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

In [12]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
# joblib.dump(___, 'explore_<Nama Algoritma>_classification.h5')

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [13]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

In [14]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

In [15]:
# Menyimpan Model hasil tuning
# import joblib
# joblib.dump(__, 'tuning_classification.h5')

End of Code